name: Matrix Testing (Advanced)

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]
        include:
          - python-version: 3.10
            python-version-short: "3.10"
          - python-version: 3.11
            python-version-short: "3.11"
          - python-version: 3.12
            python-version-short: "3.12"
    
    defaults:
      run:
        working-directory: backend
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          set -e
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-test.txt
      
      - name: Run tests with Python ${{ matrix.python-version }}
        run: |
          set -e
          pip install pytest-cov
          pytest --cov=app --cov-report=xml --cov-report=term-missing
      
      - name: Upload coverage for Python ${{ matrix.python-version }}
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-py${{ matrix.python-version-short }}
          path: backend/coverage.xml 